# Default values for iorad.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
#
replicaCount: 1

revision:

image:
  repository: iorad/app
  tag: develop
  pullPolicy: IfNotPresent

nameOverride: ""

fullnameOverride: ""

lifecycle: {}

livenessProbe: {}

configMapEnv: {}

secretEnv: {}

volumeMounts: {}

volumes: {}

service:
  type: ClusterIP
  port: 8080

ingress: {}

ingressRewrite: {}

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

mysql:
  enabled: false
  imageTag: 5.7

migration:
  enabled: false

redis:
  enabled: true

maildev:
  enabled: false
